# /clock:
#   depth: 10
#   durability: volatile
#   history: keep_last
#   reliability: best_effort
/sensing/lidar/concatenated/pointcloud:
  depth: 10
  durability: volatile
  history: keep_last
  reliability: best_effort